### PR TITLE
Feature/target single markdown file

### LINKED ISSUE #25: Readme.md in Root Directory not recognised, infinite loop
He, 
since end of last week I get the following Error Message:

> Started image server with image folder route '/github/workspace/.github/pictures'.
> Markdown files found: Readme.md
> (node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/github/workspace/.Readme.md'
>     at Object.openSync (fs.js:462:3)
>     at Object.readFileSync (fs.js:364:35)
>     at GetFileBody (/markdown-to-pdf.js:113:12)
>     at /markdown-to-pdf.js:267:21
> (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My .yml:
> uses: baileyjm02/markdown-to-pdf@v1
>         with:
>           input_dir: .
>           output_dir: .
>           image_import: .github/pictures  #Uncomment if u use imgges in your Readme.md
>           images_dir: .github/pictures     #Uncomment if u use imgges in your Readme.md
>           build_html: false

Since my "input_dir" is root but can not be empty I set it to ".". Worked till last week. 
Obviously the "." causes the Problem:
 
> no such file or directory, open '/github/workspace/.Readme.md' 

Thank you

### LINKED ISSUE #27: Target single markdown file
As discussed in #26, the input_dir should also accept a single file path. Two options for completing this are the following:
- Check if the path ends in `.md` (or `.markdown`) and if so only pass a return array with a length of one.
- Check if the path is a directory, if not, pass the path into the array directly which will result in a length of one.

<div type='discussions-op-text'>

<sup>Originally posted by @tomking July 16, 2021</sup>
Hello, I see that the action takes an input directory to pull .md files from for conversion. I was wondering if it is possible to target a single .md file rather than an entire directory? I didn't see anything about this in the readme, apologies if I missed it and thank you for your time!</div>

### PR DESCRIPTION
**Pull request by BaileyJM02**
Awesome work by @tomking for allowing a single file to be built which resolves #25 and #27.

## Backwards Compatible Changes

`input_dir` is now `input_path` and now accepts both a directory or a single file.

## Depreciations
- **`input_dir`** Should be replaced with `input_path`. (*`input_dir` is still accepted.*)

### CODE REVIEW

**Comment by BaileyJM02** [comment]
Review is on halt until nektos/act#744 is resolved due to inability to review and test.

**Comment by radnov** [comment]
@BaileyJM02 I'd really like to be able to only target a single file instead of a whole dir. Currently I bypass this "issue" by having a separate dir just for the `.md` files that need to be converted. 

Is this enhancement going to be merged? Wondering if [your last comment](https://github.com/BaileyJM02/markdown-to-pdf/pull/29#issuecomment-887399879) is still valid. 🤔

**Comment by BaileyJM02** [comment]
Hi @radnov, you're correct, my last comment is out of date. I'll get this reviewed and merged this weekend for you 👍

**Comment by BaileyJM02** [comment]
Hey, @radnov sorry for the delay here, there are still some issues with M1 support which makes testing a little difficult 😅 (https://github.com/puppeteer/puppeteer/issues/7916)


Nevertheless, I'm making a release now so hopefully all goes to plan 👍

**Pull request merged**
